"""Initial migration.

Revision ID: 5a5e5563dc60
Revises: 
Create Date: 2024-05-22 15:09:08.660359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a5e5563dc60'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('your_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch', sa.String(length=64), nullable=False),
    sa.Column('cgpa', sa.Float(), nullable=False),
    sa.Column('internships', sa.Integer(), nullable=False),
    sa.Column('backlogs', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=64), nullable=False),
    sa.Column('placed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('your_model')
    # ### end Alembic commands ###
